package org.sid.notificationservice.model;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
@Entity
@Table(name = "delivery_methods") // Specifies the table name in the database
@Data // Lombok annotation to generate getters, setters, toString, and other utility methods
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@Builder // Lombok annotation to provide a builder pattern for this class
public class DeliveryMethod {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the delivery method

    //@Column(nullable = false, unique = true) // Uncomment to enforce non-null and unique constraints
    private String name; // Name of the delivery method (e.g., Email, SMS, Push Notification)

    //@Column(nullable = false) // Uncomment to enforce non-null constraint
    private String description; // Description of the delivery method

    // Additional attributes for Email delivery method
    private String smtpHost; // SMTP host for email delivery
    private int smtpPort; // SMTP port for email delivery
    private String smtpUsername; // Username for SMTP authentication
    private String smtpPassword; // Password for SMTP authentication

    // Additional attributes for SMS delivery method
    private String smsApiUrl; // API URL for sending SMS
    private String smsApiKey; // API key for SMS authentication
    private String smsSenderId; // Sender ID for SMS messages

}
