package org.sid.notificationservice.model;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "notifications") // Specifies the table name in the database
@Data // Lombok annotation to generate getters, setters, toString, and other utility methods
@AllArgsConstructor // Lombok annotation to generate a constructor with all fields
@NoArgsConstructor // Lombok annotation to generate a no-argument constructor
@Builder // Lombok annotation to provide a builder pattern for this class
public class Notification {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the notification

    @ManyToMany // Defines a many-to-many relationship with User
    @JoinTable(name = "notification_user", // Specifies the join table name
            joinColumns = @JoinColumn(name = "notification_id"), // Column for the notification side of the relationship
            inverseJoinColumns = @JoinColumn(name = "user_id")) // Column for the user side of the relationship
    private List<User> users; // List of users associated with this notification

    @Column(length = 1000) // Specifies the maximum length of the content field
    private String content; // Content of the notification

    @ManyToOne // Defines a many-to-one relationship with NotificationType
    private NotificationType type; // The type of the notification

    private Date creationDate; // Date when the notification was created

    @ManyToOne // Defines a many-to-one relationship with Delivery
    @JoinColumn(name = "delivery_id") // Specifies the foreign key column in the notifications table
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) // Prevents this field from being serialized in JSON responses
    private Delivery delivery; // Associated delivery for this notification

}
