package org.sid.notificationservice.model;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Data @AllArgsConstructor @NoArgsConstructor @Builder
@Table(name = "notification_types")
public class NotificationType {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the notification type

    private String name; // Name of the notification type (e.g., Event, Salary Change)

    @OneToMany(mappedBy = "notificationType") // Defines a one-to-many relationship with the Template entity
    private List<Template> templates; // List of templates associated with this notification type

}