package org.sid.notificationservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "sectors")
@Data @AllArgsConstructor @NoArgsConstructor @Builder
public class Sector {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the sector

    private String name; // Name of the sector

    @Column(length = 1000) // Specifies the maximum length of the description field
    private String description; // Description of the sector

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) // Prevents this field from being serialized in JSON responses
    @OneToMany(mappedBy = "sector") // Defines a one-to-many relationship with the User entity
    private List<User> users; // List of users associated with this sector

}
