package org.sid.notificationservice.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "templates")
@Data @AllArgsConstructor @NoArgsConstructor @Builder
public class Template {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the template

    private String title; // Title of the template

    @Column(length = 1000) // Specifies the maximum length of the body field
    private String body; // Main content of the template

    private Date creationDate; // Date when the template was created

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) // Prevents this field from being serialized in JSON responses
    @ManyToOne // Defines a many-to-one relationship with the NotificationType entity
    @JoinColumn(name = "notification_type_id") // Specifies the foreign key column in this table referencing NotificationType
    private NotificationType notificationType; // The notification type associated with this template

}
