package org.sid.notificationservice.model;


import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "user_notification_delivery")
@Data @AllArgsConstructor @NoArgsConstructor @Builder
public class UserNotificationDelivery {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID should be generated by the database
    private Long id; // Unique identifier for the user notification delivery

    @ManyToOne // Defines a many-to-one relationship with the User entity
    @JoinColumn(name = "user_id") // Specifies the foreign key column in this table referencing User
    private User user; // The user associated with this notification delivery

    @ManyToOne // Defines a many-to-one relationship with the Notification entity
    @JoinColumn(name = "notification_id") // Specifies the foreign key column in this table referencing Notification
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) // Prevents this field from being serialized in JSON responses
    private Notification notification; // The notification being delivered to the user

    private boolean delivered; // Indicates whether the notification has been delivered

    private LocalDateTime deliveryTimestamp; // Timestamp of when the notification was delivered
}
